print('')
print("we would like to get your personal data in order to generate your personal card")
print('')
name = input("Enter your name: ")
surname = input("Enter your last name: ")
print('')
print("Your personal card is ready, please check it out")
print('')
print(name.__hash__())
print(surname.isprintable())